package com.ygy.model;

public class SysRoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.Sys_User_id
     *
     * @mbggenerated
     */
    private Integer sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.Sys_Role_id
     *
     * @mbggenerated
     */
    private Integer sysRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.id
     *
     * @return the value of sys_role_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.id
     *
     * @param id the value for sys_role_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.Sys_User_id
     *
     * @return the value of sys_role_user.Sys_User_id
     *
     * @mbggenerated
     */
    public Integer getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.Sys_User_id
     *
     * @param sysUserId the value for sys_role_user.Sys_User_id
     *
     * @mbggenerated
     */
    public void setSysUserId(Integer sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.Sys_Role_id
     *
     * @return the value of sys_role_user.Sys_Role_id
     *
     * @mbggenerated
     */
    public Integer getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.Sys_Role_id
     *
     * @param sysRoleId the value for sys_role_user.Sys_Role_id
     *
     * @mbggenerated
     */
    public void setSysRoleId(Integer sysRoleId) {
        this.sysRoleId = sysRoleId;
    }
}