package com.ygy.model;

import java.util.List;

public class Sysuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysUser.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysUser.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysUser.password
     *
     * @mbggenerated
     */
    private String password;
    private List<SysRole> roles;

    public void setRoles(List<SysRole> roles) {
        this.roles = roles;
    }

    public List<SysRole> getRoles() {
        return roles;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysUser.id
     *
     * @return the value of sysUser.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysUser.id
     *
     * @param id the value for sysUser.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysUser.username
     *
     * @return the value of sysUser.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysUser.username
     *
     * @param username the value for sysUser.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysUser.password
     *
     * @return the value of sysUser.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysUser.password
     *
     * @param password the value for sysUser.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}