package com.ygy.mapper;

import com.ygy.model.Sysuser;
import com.ygy.model.SysuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int countByExample(SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int deleteByExample(SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int insert(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int insertSelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    List<Sysuser> selectByExample(SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    Sysuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sysuser record, @Param("example") SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sysuser record, @Param("example") SysuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysUser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sysuser record);
    Sysuser findByUserName(String username);
}