package com.ygy.mapper;

import com.ygy.model.Test;
import com.ygy.model.TestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Nov 23 17:56:06 CST 2017
     */
    int countByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Nov 23 17:56:06 CST 2017
     */
    int deleteByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Nov 23 17:56:06 CST 2017
     */
    int insert(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Nov 23 17:56:06 CST 2017
     */
    int insertSelective(Test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Nov 23 17:56:06 CST 2017
     */
    List<Test> selectByExample(TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Nov 23 17:56:06 CST 2017
     */
    int updateByExampleSelective(@Param("record") Test record, @Param("example") TestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Nov 23 17:56:06 CST 2017
     */
    int updateByExample(@Param("record") Test record, @Param("example") TestExample example);

    /**
     *
     * 通过id查询
     * @param id
     * @return
     */
    List<Test> selectById(int id);

    /**
     * 添加
     * @since 2017/11/23
     * @param test
     */
    void insertBean(Test test);

    /**
     * 删除
     * @param id
     */
    int deletById(int id);

    /**
     *修改
     * @param test
     */
    void updateBean(Test test);

    /**
     * 通过名字查询
     * @param name
     * @return
     */
    List<Test> selectByName(String name);
}