spring:
        datasource:
                name: test
                url: jdbc:mysql://localhost/s1?characterEncoding=utf-8
                username: root
                password: ygy
                # 使用druid数据源
                type: com.alibaba.druid.pool.DruidDataSource
                driver-class-name: com.mysql.jdbc.Driver
                filters: stat
                maxActive: 20
                initialSize: 1
                maxWait: 60000
                minIdle: 1
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxOpenPreparedStatements: 20
        thymeleaf:
          cache: false
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package:   #包别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    cache-names: ygy
    caches: ygy



debug: true
##pagehelper分页插件
pagehelper:
#    helperDialect: mysql
    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
    offset-as-page-num: true
    row-bounds-with-count: true
#    dialect: mysql
